# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuickStat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuickStat
  pod 'Alamofire', '5.6.4'
  
  target 'QuickStatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuickStatUITests' do
    # Pods for testing
  end

end
