# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Round' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Round
  pod 'PocketSVG', '~> 2.6'

  target 'RoundTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RoundUITests' do
    # Pods for testing
  end

end
